import type { Metadata } from 'next';
import type { ILayout } from 'types/common';

import 'asset/styles/login.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function LoginLayout({ children }: ILayout) {
  return <>{children}</>;
}
