import QueryWrapper from 'helpers/queryWrapper';
import SessionProvider from 'components/templates/sessionProvider';
import ThemeWrapper from 'components/templates/wrapper';
import Header from 'components/organisms/header';

import type { Metadata } from 'next';

import 'asset/styles/globals.css';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <SessionProvider>
        <ThemeWrapper>
          <body>
            <QueryWrapper>
              <Header />
              {children}
            </QueryWrapper>
          </body>
        </ThemeWrapper>
      </SessionProvider>
    </html>
  );
}
